"""create protocol tables

Revision ID: 27eef86f6d71
Revises: 61f75c56f53f
Create Date: 2025-11-15 21:01:42.251079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eef86f6d71'
down_revision: Union[str, None] = '61f75c56f53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'THERAPIST', 'CLINIC_ADMIN', 'MEDICAL_DIRECTOR', 'PLATFORM_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('therapy_type', sa.Enum('PSILOCYBIN', 'MDMA', 'KETAMINE', 'LSD', 'IBOGAINE', 'OTHER', name='therapytype'), nullable=False),
    sa.Column('condition_treated', sa.String(length=255), nullable=False),
    sa.Column('evidence_level', sa.Enum('FDA_APPROVED', 'PHASE_3', 'PHASE_2', 'PHASE_1', 'PRECLINICAL', 'CLINICAL_PRACTICE', name='evidencelevel'), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('evidence_sources', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_id'), 'protocols', ['id'], unique=False)
    op.create_table('protocol_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('SCREENING', 'PREPARATION', 'DOSING', 'INTEGRATION', 'DECISION_POINT', 'FOLLOWUP', name='steptype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('required_roles', sa.JSON(), nullable=True),
    sa.Column('documentation_template_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_rules', sa.JSON(), nullable=True),
    sa.Column('branch_outcomes', sa.JSON(), nullable=True),
    sa.Column('clinical_scales', sa.JSON(), nullable=True),
    sa.Column('vitals_monitoring', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_steps_id'), 'protocol_steps', ['id'], unique=False)
    op.create_table('safety_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_step_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('override_allowed', sa.String(length=10), nullable=False),
    sa.Column('override_requirements', sa.JSON(), nullable=True),
    sa.Column('evidence_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_step_id'], ['protocol_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_checks_id'), 'safety_checks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_checks_id'), table_name='safety_checks')
    op.drop_table('safety_checks')
    op.drop_index(op.f('ix_protocol_steps_id'), table_name='protocol_steps')
    op.drop_table('protocol_steps')
    op.drop_index(op.f('ix_protocols_id'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
