"""expand_therapy_type_enum_for_all_medical_treatments

Revision ID: 9106a92b39c2
Revises: d2c018453797
Create Date: 2025-11-16 12:56:47.956589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9106a92b39c2'
down_revision: Union[str, None] = 'd2c018453797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'clinics' not in existing_tables:
        op.create_table('clinics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('license_numbers', sa.JSON(), nullable=True),
        sa.Column('certifications', sa.JSON(), nullable=True),
        sa.Column('protocols_enabled', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)

    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('PATIENT', 'THERAPIST', 'CLINIC_ADMIN', 'MEDICAL_DIRECTOR', 'PLATFORM_ADMIN', name='userrole'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    if 'audit_logs' not in existing_tables:
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=255), nullable=False),
        sa.Column('resource_type', sa.String(length=100), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('changes', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
        op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
        op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)

    if 'patient_profiles' not in existing_tables:
        op.create_table('patient_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=False),
        sa.Column('medical_history', sa.JSON(), nullable=True),
        sa.Column('medications', sa.JSON(), nullable=True),
        sa.Column('contraindications', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )
        op.create_index(op.f('ix_patient_profiles_id'), 'patient_profiles', ['id'], unique=False)

    if 'protocols' not in existing_tables:
        op.create_table('protocols',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('therapy_type', sa.Enum('PSILOCYBIN', 'MDMA', 'KETAMINE', 'LSD', 'IBOGAINE', 'TESTOSTERONE', 'ESTROGEN', 'GROWTH_HORMONE', 'PEPTIDES', 'CHEMOTHERAPY', 'IMMUNOTHERAPY', 'RADIATION', 'STEM_CELL', 'PLATELET_RICH_PLASMA', 'EXOSOME', 'GENE_THERAPY', 'CRISPR', 'CAR_T', 'LONGEVITY', 'OTHER', name='therapytype'), nullable=False),
        sa.Column('condition_treated', sa.String(length=255), nullable=False),
        sa.Column('evidence_level', sa.Enum('FDA_APPROVED', 'PHASE_3', 'PHASE_2', 'PHASE_1', 'PRECLINICAL', 'CLINICAL_PRACTICE', name='evidencelevel'), nullable=False),
        sa.Column('overview', sa.Text(), nullable=True),
        sa.Column('duration_weeks', sa.Integer(), nullable=True),
        sa.Column('total_sessions', sa.Integer(), nullable=True),
        sa.Column('evidence_sources', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_protocols_id'), 'protocols', ['id'], unique=False)

    if 'therapist_profiles' not in existing_tables:
        op.create_table('therapist_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=True),
        sa.Column('license_type', sa.String(length=50), nullable=False),
        sa.Column('license_number', sa.String(length=100), nullable=False),
        sa.Column('license_state', sa.String(length=10), nullable=False),
        sa.Column('specialties', sa.JSON(), nullable=True),
        sa.Column('certifications', sa.JSON(), nullable=True),
        sa.Column('protocols_certified', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )
        op.create_index(op.f('ix_therapist_profiles_id'), 'therapist_profiles', ['id'], unique=False)

    if 'protocol_steps' not in existing_tables:
        op.create_table('protocol_steps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('protocol_id', sa.Integer(), nullable=False),
        sa.Column('sequence_order', sa.Integer(), nullable=False),
        sa.Column('step_type', sa.Enum('SCREENING', 'PREPARATION', 'DOSING', 'INTEGRATION', 'DECISION_POINT', 'FOLLOWUP', name='steptype'), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('required_roles', sa.JSON(), nullable=True),
        sa.Column('documentation_template_id', sa.Integer(), nullable=True),
        sa.Column('evaluation_rules', sa.JSON(), nullable=True),
        sa.Column('branch_outcomes', sa.JSON(), nullable=True),
        sa.Column('clinical_scales', sa.JSON(), nullable=True),
        sa.Column('vitals_monitoring', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_protocol_steps_id'), 'protocol_steps', ['id'], unique=False)

    if 'treatment_plans' not in existing_tables:
        op.create_table('treatment_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('therapist_id', sa.Integer(), nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=True),
        sa.Column('protocol_id', sa.Integer(), nullable=False),
        sa.Column('protocol_version', sa.String(length=50), nullable=False),
        sa.Column('status', sa.Enum('SCREENING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='treatmentstatus'), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('estimated_completion', sa.DateTime(), nullable=True),
        sa.Column('customizations', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
        sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)

    if 'safety_checks' not in existing_tables:
        op.create_table('safety_checks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('protocol_step_id', sa.Integer(), nullable=False),
        sa.Column('check_type', sa.String(length=100), nullable=False),
        sa.Column('condition', sa.JSON(), nullable=False),
        sa.Column('severity', sa.String(length=50), nullable=False),
        sa.Column('override_allowed', sa.String(length=10), nullable=False),
        sa.Column('override_requirements', sa.JSON(), nullable=True),
        sa.Column('evidence_source', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['protocol_step_id'], ['protocol_steps.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_safety_checks_id'), 'safety_checks', ['id'], unique=False)

    if 'treatment_sessions' not in existing_tables:
        op.create_table('treatment_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('treatment_plan_id', sa.Integer(), nullable=False),
        sa.Column('protocol_step_id', sa.Integer(), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(), nullable=False),
        sa.Column('actual_start', sa.DateTime(), nullable=True),
        sa.Column('actual_end', sa.DateTime(), nullable=True),
        sa.Column('therapist_id', sa.Integer(), nullable=False),
        sa.Column('location', sa.String(length=50), nullable=False),
        sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['protocol_step_id'], ['protocol_steps.id'], ),
        sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_treatment_sessions_id'), 'treatment_sessions', ['id'], unique=False)

    if 'session_documentation' not in existing_tables:
        op.create_table('session_documentation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('treatment_session_id', sa.Integer(), nullable=False),
        sa.Column('vitals', sa.JSON(), nullable=True),
        sa.Column('clinical_scales', sa.JSON(), nullable=True),
        sa.Column('therapist_notes', sa.Text(), nullable=True),
        sa.Column('patient_subjective_notes', sa.Text(), nullable=True),
        sa.Column('adverse_events', sa.JSON(), nullable=True),
        sa.Column('decision_point_evaluations', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['treatment_session_id'], ['treatment_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_session_documentation_id'), 'session_documentation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_documentation_id'), table_name='session_documentation')
    op.drop_table('session_documentation')
    op.drop_index(op.f('ix_treatment_sessions_id'), table_name='treatment_sessions')
    op.drop_table('treatment_sessions')
    op.drop_index(op.f('ix_safety_checks_id'), table_name='safety_checks')
    op.drop_table('safety_checks')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_protocol_steps_id'), table_name='protocol_steps')
    op.drop_table('protocol_steps')
    op.drop_index(op.f('ix_therapist_profiles_id'), table_name='therapist_profiles')
    op.drop_table('therapist_profiles')
    op.drop_index(op.f('ix_protocols_id'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_patient_profiles_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
