"""create treatment tables

Revision ID: d0d485f3efc6
Revises: 27eef86f6d71
Create Date: 2025-11-15 21:09:41.936562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d485f3efc6'
down_revision: Union[str, None] = '27eef86f6d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('protocol_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCREENING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='treatmentstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('customizations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)
    op.create_table('treatment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=False),
    sa.Column('protocol_step_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_step_id'], ['protocol_steps.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_sessions_id'), 'treatment_sessions', ['id'], unique=False)
    op.create_table('session_documentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_session_id', sa.Integer(), nullable=False),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('clinical_scales', sa.JSON(), nullable=True),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.Column('patient_subjective_notes', sa.Text(), nullable=True),
    sa.Column('adverse_events', sa.JSON(), nullable=True),
    sa.Column('decision_point_evaluations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_session_id'], ['treatment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_documentation_id'), 'session_documentation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_documentation_id'), table_name='session_documentation')
    op.drop_table('session_documentation')
    op.drop_index(op.f('ix_treatment_sessions_id'), table_name='treatment_sessions')
    op.drop_table('treatment_sessions')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    # ### end Alembic commands ###
